### ISSUE TITLE
本地跑不起来

### ISSUE THREAD

**Issue by adminkk** [Logic-Flow/turbo-client#2]
![image](https://user-images.githubusercontent.com/31362054/190995331-c35f43a9-033c-4b53-9fa7-21516e92da48.png)

1.github 下载到本地
2.npm install
3.npm run dev

**Comment by hzwjs** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/8175184/195056828-a6c7abff-4e82-4fa9-a975-9fab43a307ee.png">
将 .env.development 文件中注释放开就可以跑起来了

**Comment by adminkk** [comment]
谢谢 已解决
